services:
  app:
    build:
      context: .  # Собираем образ из текущей директории
      dockerfile: Dockerfile
    image: wildfire-detection:latest  # Образ, который будет создан
    command: ["fastapi", "dev", "cmd/service.py", "--host", "0.0.0.0", "--port", "8000", "--proxy-headers"]
    ports:
      - "8000:8000"
    restart: unless-stopped

  worker:
    image: wildfire-detection:latest
    command: ["python", "-u", "cmd/worker.py"]
    depends_on:
      - app
    restart: unless-stopped